GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Eskos Second Blog",
    "author": "Esko Poutanen",
    "url": "https://eskosthoughts.blog",
    "likes": 567812
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "eskop",
    "name": "Esko Poutanen",
    "password": "salasana"
}