GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVza29wIiwiaWQiOiI2M2VhNDg0MjljYmM5NmM0NDhjMGI2MjMiLCJpYXQiOjE2NzYzNjQ2NjV9.Z9HBx08z2nSmuLM_GX6p3Aves6jyTDFwKYeItVYH7W4

{
    "title": "Eskos Sixth Blog",
    "author": "Esko Poutanen",
    "url": "https://eskosthoughtsmore.blog",
    "likes": 6
}

###
DELETE http://localhost:3001/api/blogs/63ea5ed2271f5bb1edcf85be

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "eskop",
    "name": "Esko Poutanen",
    "password": "salasana"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "eskop",
  "password": "salasana"
}