GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/63e3d1cd3e13d7921b6af770

###
DELETE http://localhost:3001/api/persons/63e49cedc293293fb7b3063c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Esko",
    "number": "044-3391596"
}

###
PUT http://localhost:3001/api/persons/63e50eac2a12900c1edbf322
Content-Type: application/json

{
    "name": "Changed Esko",
    "number": "044-3391596"
}