GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/63e49cedc293293fb7b3063c

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Esko",
    "number": "555 666 777"
}